SELECT * FROM STUDENT WHERE AGE BETWEEN 30 AND 45;

SELECT NAME FROM STUDENT;

SELECT * FROM STUDENT WHERE NAME ILIKE  '%J%';

SELECT * FROM  STUDENT WHERE AGE < ID;

SELECT * FROM  STUDENT ORDER BY  AGE ASC ;
